###
GET http://localhost:8085/?username=test

###
GET http://localhost:8085/gender?gender=男

###
GET http://localhost:8085/accountType?accountType=0

###
POST http://localhost:8085/
Content-Type: application/json

{
  "username": "test",
  "password": "content",
  "gender": "秀吉",
  "accountType": "ORDINARY"
}

###
POST http://localhost:8085/
Content-Type: application/json

{
  "username": "test",
  "password": "content",
  "gender": "com.muyuanjin.enumerate.Gender:MALE",
  "accountType": "ORDINARY"
}

###
POST http://localhost:8085/
Content-Type: application/json

{
  "username": "test1",
  "password": "content",
  "gender": 1,
  "accountType": "GUEST"
}

