###
GET http://localhost:8085/?username=test

###
GET http://localhost:8085/show?gender=男

###
POST http://localhost:8085/
Content-Type: application/json

{
  "username": "test",
  "password": "content",
  "gender": "未知"
}

###
POST http://localhost:8085/
Content-Type: application/json

{
  "username": "test",
  "password": "content",
  "gender": "com.muyuanjin.enumerate.Gender:MALE"
}

###
POST http://localhost:8085/
Content-Type: application/json

{
  "username": "test1",
  "password": "content",
  "gender": 1
}

